'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pl';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        'nav.library': 'Library',
        'nav.community': 'Community',
        'nav.shop': 'Shop',
        'nav.news': 'News',
        'search.placeholder': 'Search assets...',
        'add.models': 'ADD MODELS',
        'add.plants': 'ADD PLANTS',
        'add.materials': 'ADD MATERIALS',
        'add.vehicles': 'ADD VEHICLES',
        'add.characters': 'ADD CHARACTERS',
        'add.scenes': 'ADD SCENES',
        'add.addons': 'ADD ADDONS',
        'menu.file': 'File',
        'menu.file_import': 'Import Asset',
        'menu.file_sync': 'Sync Library',
        'menu.file_logout': 'Logout',
        'menu.edit': 'Edit',
        'menu.edit_settings': 'Settings',
        'menu.view': 'View',
        'menu.view_chat': 'Toggle Chat',
        'menu.view_sidebar': 'Toggle Sidebar',
        'menu.view_grid': 'Grid Size',
        'menu.view_grid_items': 'Items',
        'menu.connect': 'Connect',
        'menu.connect_status': 'Blender Status',
        'menu.connect_reconnect': 'Reconnect Blender',
        'menu.help': 'Help',
        'menu.help_about': 'About',
        'menu.help_docs': 'Documentation',
        'menu.help_console': 'System Console',
        'plugin.download': 'Download Addon',
        'plugin.download_36': 'Download Addon 3.6',
        'coffee.support': 'Support My Work',
        'coffee.button': 'Buy Me a Coffee',
        'auth.welcome': 'Welcome to 3DBRIDGE',
        'auth.sign_in': 'Sign In',
        'auth.sign_up': 'Sign Up',
        'auth.create_account': 'Create an Account',
        'auth.login_sub': 'Sign in to access your assets and chat',
        'auth.register_sub': 'Join the community of 3D artists',
        'auth.username': 'Username',
        'auth.email': 'Email Address',
        'auth.password': 'Password',
        'auth.no_account': "Don't have an account? Sign up",
        'auth.have_account': "Already have an account? Sign in",
        'auth.success_login': 'Welcome back!',
        'auth.success_register': 'Account created successfully!',
        'auth.failed': 'Authentication failed',
        'auth.error': 'Something went wrong',
        'auth.verify_title': 'Verify Email',
        'auth.verify_sub': 'Enter the 8-character code sent to your email',
        'auth.verify_code': 'Verification Code',
        'auth.verify_btn': 'Verify & Complete',
        'auth.resend': "Didn't receive a code? Resend",
        'auth.verified_success': 'Email verified! Welcome aboard.',
        'lib.no_assets': 'No assets found in library.',
        'lib.no_matching': 'No matching assets found',
        'lib.clear_filters': 'Try clearing your filters to see more content.',
        'lib.clear_btn': 'Clear Filters',
        'lib.path': 'Library Path',
        'lib.my_library': 'My Library',
        'lib.user_library': "'S LIBRARY",
        'lib.add_prefix': '+',
        'lib.user_library_prefix': 'LIBRARY',
        'lib.add_asset': 'Add Asset',
        'lib.addon_package': 'Addon Package',
        'lib.export_success': 'Asset successfully exported to Blender!',
        'lib.export_loading': 'Exporting {name} in {res}...',
        'lib.sending': 'Sending...',
        'lib.favorites': 'Favorites',
        'lib.downloaded': 'Downloaded',
        'lib.cart': 'Cart',
        'lib.checkout': 'Checkout Now',
        'lib.scanning': 'Scanning & Packing...',
        'lib.cart_empty': 'Your cart is empty',
        'lib.antivirus_msg': 'Each folder is scanned for threats before zipping.',
        'lib.failed': 'Error',
        'lib.offline': 'Blender Offline',
        'lib.send_btn': 'Send to Blender',
        'lib.guest': 'Guest',
        'lib.no_preview': 'NO PREVIEW',
        'lib.interactive_render': 'Interactive Render Active',
        'type.surface': 'Surface',
        'type.3d': '3D Asset',
        'type.3dplant': '3D Plant',
        'type.addon': 'Blender Addon',
        'type.character': 'Character',
        'type.vehicle': 'Vehicle',
        'type.scene': 'Scene',
        'type.model': '3D MODEL',
        'cat.all': 'All',
        'cat.brick': 'Brick',
        'cat.concrete': 'Concrete',
        'cat.metal': 'Metal',
        'cat.rock': 'Rock',
        'cat.wood': 'Wood',
        'cat.plaster': 'Plaster',
        'cat.stone': 'Stone',
        'cat.fabric': 'Fabric',
        'cat.plastic': 'Plastic',
        'cat.soil': 'Soil',
        'cat.ground': 'Ground',
        'cat.bark': 'Bark',
        'cat.bare': 'Bare',
        'cat.birch': 'Birch',
        'cat.board': 'Board',
        'cat.boards': 'Boards',
        'cat.castle': 'Castle',
        'cat.ceramic': 'Ceramic',
        'cat.cliff': 'Cliff',
        'cat.cliffs': 'Cliffs',
        'cat.cobblestone': 'Cobblestone',
        'cat.corroded': 'Corroded',
        'cat.corrugated': 'Corrugated',
        'cat.crumpled': 'Crumpled',
        'cat.damage': 'Damage',
        'cat.damaged': 'Damaged',
        'cat.decals': 'Decals',
        'cat.dirty': 'Dirty',
        'cat.drywall': 'Drywall',
        'cat.dust': 'Dust',
        'cat.fine': 'Fine',
        'cat.floor': 'Floor',
        'cat.forest': 'Forest',
        'cat.granite': 'Granite',
        'cat.grass': 'Grass',
        'cat.gravel': 'Gravel',
        'cat.industrial': 'Industrial',
        'cat.interior': 'Interior',
        'cat.leaves': 'Leaves',
        'cat.leather': 'Leather',
        'cat.limestone': 'Limestone',
        'cat.marble': 'Marble',
        'cat.mud': 'Mud',
        'cat.painted': 'Painted',
        'cat.pavement': 'Pavement',
        'cat.peeling': 'Peeling',
        'cat.roof': 'Roof',
        'cat.rubble': 'Rubble',
        'cat.rusty': 'Rusty',
        'cat.sand': 'Sand',
        'cat.slate': 'Slate',
        'cat.snow': 'Snow',
        'cat.tile': 'Tile',
        'cat.urban': 'Urban',
        'cat.wall': 'Wall',
        'cat.water': 'Water',
        'cat.weed': 'Weed',
        'cat.weathered': 'Weathered',
        'cat.moss': 'Moss',
        'cat.debris': 'Debris',
        'cat.construction': 'Construction',
        'group.3d_models': '3D Models',
        'group.3d_plants': '3D Plants',
        'group.materials': 'Materials',
        'group.vehicles': 'Vehicles',
        'group.characters': 'Characters',
        'group.scenes': 'Scenes',
        'group.addons': 'Addons',
        'modal.create_asset': 'Create Asset',
        'modal.new_asset': 'New Asset',
        'modal.new_addon': 'New Addon',
        'modal.asset': 'Asset',
        'modal.addon': 'Addon',
        'modal.name': 'Name',
        'modal.category': 'Category',
        'modal.type': 'Type',
        'modal.files': 'Asset Files',
        'modal.addon_file': 'Addon File (.zip)',
        'modal.click_upload': 'Select maps or FBX files',
        'modal.click_upload_zip': 'Click to upload zip',
        'modal.selected': 'selected',
        'modal.preview': '3D Material Preview',
        'modal.files_addon_label': 'Addon File (.zip)',
        'modal.files_asset_label': 'Asset Files',
        'modal.category_placeholder': 'e.g. Tools',
        'modal.cancel': 'Cancel',
        'modal.add_addon': 'Add Addon',
        'modal.fill_fields': 'Please fill all fields and select files',
        'modal.zip_error': 'Addons must be .zip files',
        'modal.asset_success': 'Asset created successfully!',
        'modal.addon_success': 'Addon created successfully!',
        'modal.asset_name_placeholder': 'Asset name...',
        'modal.addon_name_placeholder': 'Addon name...',
        'grid.cols_tooltip': '{cols} items per row',
        'settings.path_placeholder': 'E:\\Megascans Library\\Downloaded',
        'settings.path_hint': 'This folder should contain your assetsData.json and downloaded Megascans assets.',
        'settings.current': 'Current',
        'settings.not_set': 'Not set',
        'status.connected': 'CONNECTED',
        'status.offline': 'OFFLINE',
        'chat.general': 'General',
        'chat.direct': 'Direct',
        'chat.contacts': 'Contacts',
        'chat.back': 'Back to Chat',
        'chat.placeholder': 'Type a message...',
        'chat.connected_to': 'Connected to {id}',
        'chat.send': 'Send',
        'chat.title': 'Community Chat',
        'chat.room': 'Room',
        'chat.private_chat': 'Private Chat',
        'chat.general_chat': 'General Chat',
        'chat.starting_chat': 'Starting chat with {user}...',
        'chat.chatting_with': 'Chatting with {user}',
        'chat.start_failed': 'Failed to start chat',
        'chat.you': 'You',
        'chat.select': 'Select',
        'chat.active': 'Active',
        'chat.end': 'End',
        'chat.peer_disconnected': 'Peer disconnected',
        'chat.connection_failed': 'Connection failed',
        'chat.invalid_id': 'Invalid ID',
        'chat.reconnecting': 'Reconnecting to server...',
        'chat.send_failed': 'Failed to send message',
        'chat.request_sent': 'Request broadcasted!',
        'chat.request_failed': 'Failed to send request',
        'chat.fulfill_success': 'Asset fulfilled!',
        'chat.fulfill_failed': 'Failed to fulfill',
        'chat.sending_file': 'Sending {name}...',
        'chat.id_copied': 'ID copied to clipboard',
        'chat.no_messages': 'No messages yet.',
        'chat.connect_to_start': 'Connect to a peer to start sharing assets.',
        'chat.asset_wanted': 'Asset Wanted',
        'chat.fulfilled': 'Fulfilled',
        'chat.requested_by': 'Requested by ',
        'chat.fulfilled_by': ' • Fulfilled by ',
        'chat.download_asset': 'Download Asset',
        'chat.no_peer_id': 'No Peer ID found for requester',
        'chat.connect_direct': 'Connect Direct P2P',
        'chat.upload_to_fulfill': 'Upload to Fulfill',
        'chat.request_asset': 'Request Asset',
        'chat.asset_name_placeholder': 'Asset name (e.g. Nordic Rock)...',
        'chat.broadcast_request': 'Broadcast Request',
        'chat.connection_error': 'Connection error',
        'chat.peer_id_placeholder': 'Peer ID...',
        'chat.connected_to_peer': 'Connected to Peer',
        'chat.members_online': 'members online',
        'chat.private_session': 'Private Session',
        'chat.not_connected': 'Not Connected',
        'chat.broadcast': 'Broadcast',
        'chat.press_enter': 'Press Enter to send',
        'chat.online': 'online',
        'chat.peer': 'Peer',
        'chat.topic_set_by': 'Topic is set by %nick% on %date%',
        'chat.start_chatting_on': 'Now Talking on #%name%',
        'chat.recently': 'recently',
        'chat.channels': 'CHANNELS',
        'chat.online_users': 'ONLINE USERS',
        'chat.connect_peer': 'CONNECT PEER',
        'chat.targetId': 'Target Peer ID...',
        'chat.direct_messaging': 'Direct Messaging',
        'chat.start_conversation': 'Select a user or channel to start chatting',
        'chat.create_channel': 'Create Private Channel',
        'chat.channel_name': 'Channel Name',
        'chat.invite_users': 'Invite Users (max 2)',
        'chat.name_required': 'Channel name is required',
        'chat.member_required': 'Invite at least one member',
        'chat.max_members': 'Maximum 2 invited members',
        'chat.private': 'Private',
        'chat.cancel': 'Cancel',
        'chat.create': 'Create',
        'chat.topic_updated': 'Channel topic updated successfully',
        'chat.topic_failed': 'Failed to update channel topic',
        'chat.only_owner_topic': 'Only the channel owner can change the topic',
        'chat.invite': 'Invite to Channel',
        'chat.kick': 'Kick User',
        'chat.user_invited': 'User invited',
        'chat.invite_failed': 'Failed to invite user',
        'chat.user_kicked': 'User kicked',
        'chat.kick_failed': 'Failed to kick user',
        'lib.add_new_category': 'Add New Category',
        'modal.no_maps': 'No generated maps to save!',
        'lib.sync_success': 'Library synced successfully',
        'lib.sync_failed': 'Failed to sync library',
        'lib.sync_error': 'Network error during sync',
        'settings.path_updated': 'Library path updated! Syncing assets...',
        'settings.path_error': 'Failed to update path',
        'settings.network_error': 'Network error',
        'sys.update_soon': 'Update system will be available soon!',
        'lib.syncing': 'Syncing library assets...',
        'lib.delete_zips': 'Delete {count} transfer files',
        'chat.init_failed': 'Failed to initialize chat',
        'chat.packing': 'Packing assets for {user}...',
        'chat.pack_sent': 'Sent zip to {user}',
        'chat.pack_failed': 'Packing failed',
        'chat.pack_error': 'Internal packing error',
        'chat.receiving': 'Receiving assets...',
        'chat.unpack_success': 'Assets added to your library!',
        'chat.unpack_failed': 'Unpacking failed',
        'chat.unpack_error': 'Failed to process received zip',
        'chat.channel_created': 'Channel created',
        'chat.channel_create_failed': 'Failed to create channel',
        'chat.switching_to': 'Switching to chat with {user}',
        'chat.leave_confirm': 'Leave channel #{name}?',
        'chat.channel_deleted': 'Channel #{name} deleted (empty)',
        'chat.channel_left': 'You left #{name}',
        'chat.leave_failed': 'Failed to leave channel',
        'bug.success': 'Bug report submitted successfully!',
        'bug.error': 'Failed to submit bug report. Please try again.',
        'modal.normal_success': 'Normal map generated!',
        'modal.normal_error': 'Failed to generate normal map',
        'modal.ao_success': 'AO map generated!',
        'modal.ao_error': 'Failed to generate AO map',
        'modal.disp_success': 'Displacement map generated!',
        'modal.disp_error': 'Failed to generate Displacement map',
        'modal.roughness_success': 'Roughness map generated!',
        'modal.roughness_error': 'Failed to generate Roughness map',
        'modal.spec_success': 'Specular map generated!',
        'modal.spec_error': 'Failed to generate Specular map',
        'modal.pack_success': 'ORD map packed successfully!',
        'modal.pack_error': 'Failed to pack ORD map',
        'modal.preview_not_ready': 'Preview not ready yet',
        'modal.thumb_success': 'Thumbnail captured! Ready to create asset.',
        'modal.thumb_error': 'Failed to capture thumbnail',
    },
    pl: {
        'nav.library': 'Biblioteka',
        'nav.community': 'Społeczność',
        'nav.shop': 'Sklep',
        'nav.news': 'Nowości',
        'search.placeholder': 'Szukaj zasobów...',
        'add.models': 'DODAJ MODELE',
        'add.plants': 'DODAJ ROŚLINY',
        'add.materials': 'DODAJ MATERIAŁY',
        'add.vehicles': 'DODAJ POJAZDY',
        'add.characters': 'DODAJ POSTACIE',
        'add.scenes': 'DODAJ SCENY',
        'add.addons': 'DODAJ DODATKI',
        'menu.file': 'Plik',
        'menu.file_import': 'Importuj Zasób',
        'menu.file_sync': 'Synchronizuj',
        'menu.file_logout': 'Wyloguj',
        'menu.edit': 'Edycja',
        'menu.edit_settings': 'Ustawienia',
        'menu.view': 'Widok',
        'menu.view_chat': 'Przełącz Czat',
        'menu.view_sidebar': 'Przełącz Pasek',
        'menu.view_grid': 'Rozmiar Siatki',
        'menu.view_grid_items': 'Elementy',
        'menu.connect': 'Połącz',
        'menu.connect_status': 'Status Blendera',
        'menu.connect_reconnect': 'Połącz Ponownie',
        'menu.help': 'Pomoc',
        'menu.help_about': 'O Programie',
        'menu.help_docs': 'Dokumentacja',
        'menu.help_console': 'Konsola Systemowa',
        'plugin.download': 'Pobierz Addon',
        'plugin.download_36': 'Pobierz Addon 3.6',
        'coffee.support': 'Wesprzyj moją pracę',
        'coffee.button': 'Postaw mi kawę',
        'chat.general': 'Ogólny',
        'chat.direct': 'Bezpośredni',
        'chat.contacts': 'Kontakty',
        'chat.back': 'Wróć do czatu',
        'chat.placeholder': 'Wpisz wiadomość...',
        'chat.connected_to': 'Połączono z {id}',
        'chat.connection_error': 'Błąd połączenia',
        'chat.peer_id_placeholder': 'ID Peer...',
        'chat.connected_to_peer': 'Połączono z użytkownikiem',
        'chat.members_online': 'użytkowników online',
        'chat.private_session': 'Sesja prywatna',
        'chat.broadcast': 'Rozgłoś',
        'chat.press_enter': 'Naciśnij Enter, aby wysłać',
        'chat.online': 'użytkowników online',
        'chat.peer': 'Użytkownik',
        'chat.topic_set_by': 'Temat ustawiony przez %nick% dnia %date%',
        'chat.start_chatting_on': 'Rozmawiasz na kanale #%name%',
        'chat.recently': 'niedawno',
        'chat.channels': 'KANAŁY',
        'chat.online_users': 'UŻYTKOWNICY ONLINE',
        'chat.connect_peer': 'POŁĄCZ Z PEER',
        'chat.targetId': 'ID Peer celu...',
        'chat.direct_messaging': 'Wiadomości bezpośrednie',
        'chat.start_conversation': 'Wybierz użytkownika lub kanał, aby zacząć czatować',
        'chat.create_channel': 'Utwórz kanał prywatny',
        'chat.channel_name': 'Nazwa kanału',
        'chat.invite_users': 'Zaproś użytkowników (maks. 2)',
        'chat.name_required': 'Nazwa kanału jest wymagana',
        'chat.member_required': 'Zaproś przynajmniej jednego użytkownika',
        'chat.max_members': 'Maksymalnie 2 zaproszonych użytkowników',
        'chat.private': 'Prywatny',
        'chat.cancel': 'Anuluj',
        'chat.create': 'Utwórz',
        'chat.topic_updated': 'Temat kanału został zaktualizowany',
        'chat.topic_failed': 'Nie udało się zaktualizować tematu',
        'chat.only_owner_topic': 'Tylko właściciel kanału może zmienić temat',
        'chat.invite': 'Zaproś do kanału',
        'chat.kick': 'Wyrzuć użytkownika',
        'chat.user_invited': 'Użytkownik zaproszony',
        'chat.invite_failed': 'Błąd zapraszania użytkownika',
        'chat.user_kicked': 'Użytkownik wyrzucony',
        'chat.kick_failed': 'Błąd wyrzucania użytkownika',
        'auth.welcome': 'Witaj w CGI Bridge',
        'auth.sign_in': 'Zaloguj się',
        'auth.sign_up': 'Zarejestruj się',
        'auth.create_account': 'Utwórz konto',
        'auth.login_sub': 'Zaloguj się, aby uzyskać dostęp do zasobów i czatu',
        'auth.register_sub': 'Dołącz do społeczności artystów 3D',
        'auth.username': 'Nazwa użytkownika',
        'auth.email': 'Adres E-mail',
        'auth.password': 'Hasło',
        'auth.no_account': 'Nie masz konta? Zarejestruj się',
        'auth.has_account': 'Masz już konto? Zaloguj się',
        'auth.welcome_back': 'Witaj ponownie!',
        'auth.account_created': 'Konto utworzone pomyślnie!',
        'auth.error': 'Logowanie nieudane',
        'auth.generic_error': 'Coś poszło nie tak',
        'auth.verify_title': 'Zweryfikuj E-mail',
        'auth.verify_sub': 'Wpisz 8-znakowy kod wysłany na Twój e-mail',
        'auth.verify_code': 'Kod Weryfikacyjny',
        'auth.verify_btn': 'Zweryfikuj i Zakończ',
        'auth.resend': 'Nie otrzymałeś kodu? Wyślij ponownie',
        'auth.verified_success': 'E-mail zweryfikowany! Witaj na pokładzie.',
        'lib.no_assets': 'Nie znaleziono zasobów w bibliotece.',
        'lib.path': 'Ścieżka biblioteki',
        'lib.my_library': 'Moja Biblioteka',
        'lib.user_library': " - BIBLIOTEKA",
        'lib.favorites': 'Ulubione',
        'lib.downloaded': 'Pobrane',
        'lib.cart': 'Koszyk',
        'lib.checkout': 'Zatwierdź i Wyślij',
        'lib.scanning': 'Skanowanie i Pakowanie...',
        'lib.cart_empty': 'Twój koszyk jest pusty',
        'lib.antivirus_msg': 'Każdy folder jest skanowany pod kątem zagrożeń przed spakowaniem.',
        'lib.no_matching': 'Nie znaleziono pasujących zasobów',
        'lib.clear_filters': 'Spróbuj wyczyścić filtry, aby zobaczyć więcej treści.',
        'lib.clear_btn': 'Wyczyść filtry',
        'lib.settings_tooltip': 'Ustawienia biblioteki',
        'lib.export_success': 'Zasób pomyślnie wysłany do Blendera!',
        'lib.export_loading': 'Eksportowanie {name} w {res}...',
        'lib.sending': 'Wysyłanie...',
        'lib.exported': 'Wyeksportowano!',
        'lib.failed': 'Błąd',
        'lib.offline': 'Blender Offline',
        'lib.send_btn': 'Wyślij do Blendera',
        'lib.guest': 'Gość',
        'lib.no_preview': 'BRAK_PODGLĄDU',
        'lib.interactive_render': 'Interaktywny render aktywny',
        'lib.user_library_prefix': 'BIBLIOTEKA',
        'lib.add_prefix': '+',
        'type.surface': 'Powierzchnia',
        'type.3d': 'Model 3D',
        'type.3dplant': 'Roślina 3D',
        'type.addon': 'Dodatek Blender',
        'type.character': 'Postać',
        'type.vehicle': 'Pojazd',
        'type.scene': 'Scena',
        'type.model': 'MODEL 3D',
        'cat.all': 'Wszystkie',
        'cat.brick': 'Cegła',
        'cat.concrete': 'Beton',
        'cat.metal': 'Metal',
        'cat.rock': 'Skała',
        'cat.wood': 'Drewno',
        'cat.plaster': 'Tynk',
        'cat.stone': 'Kamień',
        'cat.fabric': 'Tkanina',
        'cat.plastic': 'Plastik',
        'cat.soil': 'Gleba',
        'cat.ground': 'Ziemia',
        'cat.bark': 'Kora',
        'cat.bare': 'Surowy',
        'cat.birch': 'Brzoza',
        'cat.board': 'Deska',
        'cat.boards': 'Deski',
        'cat.castle': 'Zamek',
        'cat.ceramic': 'Ceramika',
        'cat.cliff': 'Klif',
        'cat.cliffs': 'Klify',
        'cat.cobblestone': 'Bruk',
        'cat.corroded': 'Zkorodowany',
        'cat.corrugated': 'Falisty',
        'cat.crumpled': 'Zgnieciony',
        'cat.damage': 'Uszkodzenie',
        'cat.damaged': 'Uszkodzony',
        'cat.decals': 'Naklejki',
        'cat.dirty': 'Brudny',
        'cat.drywall': 'Gips-karton',
        'cat.dust': 'Kurz',
        'cat.fine': 'Drobny',
        'cat.floor': 'Podłoga',
        'cat.forest': 'Las',
        'cat.granite': 'Granit',
        'cat.grass': 'Trawa',
        'cat.gravel': 'Żwir',
        'cat.industrial': 'Przemysłowy',
        'cat.interior': 'Wnętrze',
        'cat.leaves': 'Liście',
        'cat.leather': 'Skóra',
        'cat.limestone': 'Wapień',
        'cat.marble': 'Marmur',
        'cat.mud': 'Błoto',
        'cat.painted': 'Malowany',
        'cat.pavement': 'Chodnik',
        'cat.peeling': 'Łuszczący się',
        'cat.roof': 'Dach',
        'cat.rubble': 'Gruz',
        'cat.rusty': 'Rdzawy',
        'cat.sand': 'Piasek',
        'cat.slate': 'Łupek',
        'cat.snow': 'Śnieg',
        'cat.tile': 'Płytka',
        'cat.urban': 'Miejski',
        'cat.wall': 'Ściana',
        'cat.water': 'Woda',
        'cat.weed': 'Chwast',
        'cat.weathered': 'Zwietrzały',
        'cat.moss': 'Mech',
        'cat.debris': 'Szczątki',
        'cat.construction': 'Budowlany',
        'group.3d_models': 'Modele 3D',
        'group.3d_plants': 'Rośliny 3D',
        'group.materials': 'Powierzchnie',
        'group.vehicles': 'Pojazdy',
        'group.characters': 'Postacie',
        'group.scenes': 'Sceny',
        'group.addons': 'Dodatki',
        'unauthorized': 'Brak autoryzacji. Zaloguj się.',
        'success.asset': 'Zasób utworzony pomyślnie!',
        'success.addon': 'Dodatek utworzony pomyślnie!',
        'error.upload': 'Błąd tworzenia zasobu',
        'settings.title': 'Ustawienia aplikacji',
        'settings.subtitle': 'Skonfiguruj swoje lokalne środowisko',
        'settings.cancel': 'Anuluj',
        'settings.save': 'Zapisz konfigurację',
        'settings.current': 'Aktualna',
        'settings.not_set': 'Nie ustawiono',
        'settings.path_placeholder': 'E:\\Megascans Library\\Downloaded',
        'settings.path_hint': 'Ten folder powinien zawierać plik assetsData.json oraz pobrane zasoby Megascans.',
        'status.connected': 'POŁĄCZONO',
        'status.offline': 'OFFLINE',
        'grid.cols_tooltip': '{cols} elementy w rzędzie',
        'chat.send': 'Wyślij',
        'chat.title': 'Czat społeczności',
        'chat.room': 'Pokój',
        'chat.private_chat': 'Czat prywatny',
        'chat.general_chat': 'Czat ogólny',
        'chat.starting_chat': 'Rozpoczynanie czatu z {user}...',
        'chat.chatting_with': 'Czatujesz z {user}',
        'chat.start_failed': 'Nie udało się rozpocząć czatu',
        'chat.you': 'Ty',
        'chat.select': 'Wybierz',
        'chat.active': 'Aktywny',
        'chat.end': 'Zakończ',
        'chat.peer_disconnected': 'Użytkownik rozłączony',
        'chat.connection_failed': 'Połączenie nieudane',
        'chat.invalid_id': 'Nieprawidłowy ID',
        'chat.reconnecting': 'Reconnectowanie z serwerem...',
        'chat.send_failed': 'Nie udało się wysłać wiadomości',
        'chat.not_connected': 'Nie połączono z rówieśnikiem',
        'chat.request_sent': 'Prośba wysłana!',
        'chat.request_failed': 'Nie udało się wysłać prośby',
        'chat.fulfill_success': 'Zasób dostarczony!',
        'chat.fulfill_failed': 'Nie udało się dostarczyć',
        'chat.sending_file': 'Wysyłanie {name}...',
        'chat.id_copied': 'ID skopiowane do schowka',
        'chat.no_messages': 'Brak wiadomości.',
        'chat.connect_to_start': 'Połącz się z kimś, aby zacząć udostępniać zasoby.',
        'chat.asset_wanted': 'Poszukiwany Zasób',
        'chat.fulfilled': 'Dostarczono',
        'chat.requested_by': 'Poprosił ',
        'chat.fulfilled_by': ' • Dostarczył ',
        'chat.download_asset': 'Pobierz Zasób',
        'chat.no_peer_id': 'Nie znaleziono Peer ID proszącego',
        'chat.connect_direct': 'Połącz Bezpośrednio P2P',
        'chat.upload_to_fulfill': 'Prześlij aby Dostarczyć',
        'chat.request_asset': 'Poproś o Zasób',
        'chat.asset_name_placeholder': 'Nazwa zasobu (np. Nordic Rock)...',
        'chat.broadcast_request': 'Rozgłoś prośbę',
        'modal.new_asset': 'Nowy Zasób',
        'modal.new_addon': 'Nowy Dodatek',
        'modal.asset': 'Zasób',
        'modal.addon': 'Dodatek',
        'modal.name': 'Nazwa',
        'modal.category': 'Kategoria',
        'modal.type': 'Typ',
        'modal.files': 'Pliki zasobu',
        'modal.addon_file': 'Plik dodatku (.zip)',
        'modal.click_upload': 'Wybierz mapy lub pliki FBX',
        'modal.click_upload_zip': 'Kliknij, aby przesłać zip',
        'modal.selected': 'wybrano',
        'modal.preview': 'Podgląd materiału 3D',
        'modal.files_addon_label': 'Plik dodatku (.zip)',
        'modal.files_asset_label': 'Pliki zasobu',
        'modal.category_placeholder': 'np. Narzędzia',
        'modal.cancel': 'Anuluj',
        'modal.create_asset': 'Utwórz zasób',
        'modal.add_addon': 'Dodaj Addon',
        'modal.fill_fields': 'Wypełnij wszystkie pola i wybierz pliki',
        'modal.zip_error': 'Dodatki muszą być plikami .zip',
        'modal.asset_success': 'Zasób utworzony pomyślnie!',
        'modal.addon_success': 'Dodatek utworzony pomyślnie!',
        'modal.asset_name_placeholder': 'Nazwa zasobu...',
        'modal.addon_name_placeholder': 'Nazwa dodatku...',
        'lib.add_new_category': 'Dodaj nową kategorię',
        'modal.no_maps': 'Brak wygenerowanych map do zapisania!',
        'lib.sync_success': 'Biblioteka zsynchronizowana pomyślnie',
        'lib.sync_failed': 'Nie udało się zsynchronizować biblioteki',
        'lib.sync_error': 'Błąd sieci podczas synchronizacji',
        'settings.path_updated': 'Ścieżka biblioteki zaktualizowana! Synchronizowanie...',
        'settings.path_error': 'Nie udało się zaktualizować ścieżki',
        'settings.network_error': 'Błąd sieci',
        'sys.update_soon': 'System aktualizacji będzie wkrótce dostępny!',
        'lib.syncing': 'Synchronizowanie zasobów biblioteki...',
        'lib.delete_zips': 'Usuń {count} plików transferu',
        'chat.init_failed': 'Nie udało się zainicjować czatu',
        'chat.packing': 'Pakowanie zasobów dla {user}...',
        'chat.pack_sent': 'Wysłano paczkę do {user}',
        'chat.pack_failed': 'Pakowanie nie powiodło się',
        'chat.pack_error': 'Wewnętrzny błąd pakowania',
        'chat.receiving': 'Odbieranie zasobów...',
        'chat.unpack_success': 'Zasoby dodane do Twojej biblioteki!',
        'chat.unpack_failed': 'Rozpakowywanie nie powiodło się',
        'chat.unpack_error': 'Nie udało się przetworzyć odebranej paczki',
        'chat.channel_created': 'Kanał utworzony',
        'chat.channel_create_failed': 'Nie udało się utworzyć kanału',
        'chat.switching_to': 'Przełączanie na czat z {user}',
        'chat.leave_confirm': 'Opuścić kanał #{name}?',
        'chat.channel_deleted': 'Kanał #{name} usunięty (pusty)',
        'chat.channel_left': 'Opuściłeś kanał #{name}',
        'chat.leave_failed': 'Nie udało się opuścić kanału',
        'bug.success': 'Zgłoszenie błędu wysłane pomyślnie!',
        'bug.error': 'Nie udało się wysłać zgłoszenia. Spróbuj ponownie.',
        'modal.normal_success': 'Mapa Normal wygenerowana!',
        'modal.normal_error': 'Nie udało się wygenerować mapy Normal',
        'modal.ao_success': 'Mapa AO wygenerowana!',
        'modal.ao_error': 'Nie udało się wygenerować mapy AO',
        'modal.disp_success': 'Mapa Displacement wygenerowana!',
        'modal.disp_error': 'Nie udało się wygenerować mapy Displacement',
        'modal.roughness_success': 'Mapa Roughness wygenerowana!',
        'modal.roughness_error': 'Nie udało się wygenerować mapy Roughness',
        'modal.spec_success': 'Mapa Specular wygenerowana!',
        'modal.spec_error': 'Nie udało się wygenerować mapy Specular',
        'modal.pack_success': 'Mapa ORD spakowana pomyślnie!',
        'modal.pack_error': 'Nie udało się spakować mapy ORD',
        'modal.preview_not_ready': 'Podgląd nie jest jeszcze gotowy',
        'modal.thumb_success': 'Zrobiono zrzut! Gotowe do zapisu.',
        'modal.thumb_error': 'Nie udało się zrobić zrzutu',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    // Persistence
    useEffect(() => {
        const saved = localStorage.getItem('app-lang') as Language;
        if (saved && (saved === 'en' || saved === 'pl')) {
            setLanguage(saved);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('app-lang', lang);
    };

    const t = (key: string) => {
        const val = (translations[language] as any)[key];
        if (val) return val;

        // Fallback for dynamic keys
        if (key.startsWith('cat.') || key.startsWith('group.')) {
            const cleanKey = key.replace(/^(cat\.|group\.)/, '');
            // specific fix: 3d -> 3D
            if (cleanKey === '3d') return '3D';

            return cleanKey
                .split('_')
                .map(w => w.charAt(0).toUpperCase() + w.slice(1))
                .join(' ');
        }

        return key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
